Variant: 7  
Tasks: 3,4,5,6,7,8,9,13,19

In [5]:
import numpy as np

In [7]:
#3
n,m,r,c = 5,5,2,2
mtr = np.ones((n,m))
mtr[r] = np.zeros(m)
mtr[:,c] = np.zeros(n)
print(mtr)

[[1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1.]]


In [8]:
#4
n,m = 5,5
mtr = np.zeros((n,m))
mtr[0] = np.arange(m)
print(mtr)

[[0. 1. 2. 3. 4.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
#5
n = 5
matrix = np.zeros((n,n))
matrix[np.arange(0,n,2)] = 1
print(matrix)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [14]:
#6
nums = input("Enter numbers")
arr = np.fromstring(nums, sep=' ')
print(np.where(arr != 0, -1, arr))

[-1. -1. -1.  0.  0. -1.]


In [15]:
#7
nums = input("Enter numbers")
arr = np.fromstring(nums, sep=' ')
print(np.where(arr == 0, -1, arr))

[ 1.  2.  3. -1. -1.  4.]


In [19]:
#8
nums = input("Enter numbers")
arr = np.fromstring(nums, sep=' ')
print("Non zeros: ", np.count_nonzero(arr))
print("Zeros: ", len(arr) - np.count_nonzero(arr))

1
2


In [27]:
#9
n = 5
print(np.flip(np.arange(n+1)))

[5 4 3 2 1 0]


In [47]:
#13
print(np.array([[0,1]*4, [1,0]*4]*4))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [53]:
#19
n = 10
print(np.around(np.linspace(0, 1, num=n+1, endpoint=False)[1:], 3))

[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]


In [56]:
# Task 2
A = np.array([
    [2,1,-5,1],
    [1,-3,0,-6],
    [0,2,-1,2],
    [1,4,-7,6]
])
B = np.array([8,9,-5, 0])

#Crammer
import copy
import numpy as np
det_A = np.linalg.det(A)
for i in np.arange(len(A)):
    a = copy.deepcopy(A)
    a[:,i] = B
    print("x", i, " = ", np.round(np.linalg.det(a) / det_A,1), sep="")

x0 = 3.0
x1 = -4.0
x2 = -1.0
x3 = 1.0


In [57]:
# Task 3
A = np.array([
    [5,3,-1],
    [2,-2,0],
    [3,-1,2]
])

B = np.array([
    [1,4,16],
    [-3,-2,0],
    [5,7,2]
])

print(2*(A - 0.5 * B) + np.matmul(A, B))

[[ 0.  9. 60.]
 [15. 10. 32.]
 [17. 19. 54.]]
